import type { Metadata } from "next";
import "./styles/globals.css";
import Sidebar from "./components/Sidebar";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "intela",
  icons: {
    icon: "/logoo.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-full h-full">
          <Sidebar />
          <div className="w-full">
            <Header />
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
